import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const dummyReservations = [
  {
    fullName: "Anna Nováková",
    email: "anna.novakova@email.com",
    confirmAdult: true,
    placement: "rameno",
    size: "stredná",
    color: "color",
    description: "Kvetinový motív s ružami a levanduľou",
    references: ["https://example.com/ref1.jpg", "https://example.com/ref2.jpg"],
    imageUrl: null,
    notes: "Klientka preferuje pastelové farby",
    contactPreferenceEmail: true,
    contactPreferenceInstagram: false,
    contactPreferencePhone: false,
    instagram: null,
    phone: null,
    agreeMarketing: true,
    agreePrivacy: true,
    allergies: false,
    allergyDescription: null,
    healthIssues: false,
    healthIssueDescription: null,
    appointmentDate: new Date("2025-08-02"),
    appointmentTime: "10:00",
    duration: 3,
    status: "pending"
  },
  {
    fullName: "Martin Svoboda",
    email: "martin.svoboda@email.com",
    confirmAdult: true,
    placement: "predlaktie",
    size: "malá",
    color: "blackwhite",
    description: "Geometrický vzor s čiarami a bodmi",
    references: ["https://example.com/ref3.jpg"],
    imageUrl: null,
    notes: "Klient chce minimalistický dizajn",
    contactPreferenceEmail: true,
    contactPreferenceInstagram: true,
    contactPreferencePhone: false,
    instagram: "@martin_svoboda",
    phone: null,
    agreeMarketing: false,
    agreePrivacy: true,
    allergies: true,
    allergyDescription: "Alergia na latex",
    healthIssues: false,
    healthIssueDescription: null,
    appointmentDate: new Date("2025-08-05"),
    appointmentTime: "14:30",
    duration: 2,
    status: "confirmed"
  },
  {
    fullName: "Eva Králová",
    email: "eva.kralova@email.com",
    confirmAdult: true,
    placement: "chrbát",
    size: "veľká",
    color: "color",
    description: "Portrét mačky s realistickým štýlom",
    references: ["https://example.com/ref4.jpg", "https://example.com/ref5.jpg", "https://example.com/ref6.jpg"],
    imageUrl: null,
    notes: "Klientka má vlastnú mačku, chce portrét",
    contactPreferenceEmail: true,
    contactPreferenceInstagram: false,
    contactPreferencePhone: true,
    instagram: null,
    phone: "+421 905 123 456",
    agreeMarketing: true,
    agreePrivacy: true,
    allergies: false,
    allergyDescription: null,
    healthIssues: false,
    healthIssueDescription: null,
    appointmentDate: new Date("2025-08-08"),
    appointmentTime: "09:00",
    duration: 5,
    status: "pending"
  },
  {
    fullName: "Peter Horváth",
    email: "peter.horvath@email.com",
    confirmAdult: true,
    placement: "noha",
    size: "stredná",
    color: "blackwhite",
    description: "Tribálny vzor s maorskými motívmi",
    references: ["https://example.com/ref7.jpg"],
    imageUrl: null,
    notes: "Klient chce tradičný tribálny štýl",
    contactPreferenceEmail: false,
    contactPreferenceInstagram: true,
    contactPreferencePhone: true,
    instagram: "@peter_horvath",
    phone: "+421 902 987 654",
    agreeMarketing: false,
    agreePrivacy: true,
    allergies: false,
    allergyDescription: null,
    healthIssues: true,
    healthIssueDescription: "Diabetes - potrebuje časté prestávky",
    appointmentDate: new Date("2025-08-11"),
    appointmentTime: "11:00",
    duration: 4,
    status: "confirmed"
  },
  {
    fullName: "Lucia Tóthová",
    email: "lucia.tothova@email.com",
    confirmAdult: true,
    placement: "zápästie",
    size: "malá",
    color: "color",
    description: "Drobné srdce s menom",
    references: ["https://example.com/ref8.jpg"],
    imageUrl: null,
    notes: "Prvé tetovanie, nervózna",
    contactPreferenceEmail: true,
    contactPreferenceInstagram: false,
    contactPreferencePhone: false,
    instagram: null,
    phone: null,
    agreeMarketing: true,
    agreePrivacy: true,
    allergies: false,
    allergyDescription: null,
    healthIssues: false,
    healthIssueDescription: null,
    appointmentDate: new Date("2025-08-14"),
    appointmentTime: "13:00",
    duration: 1,
    status: "pending"
  },
  {
    fullName: "Ján Kováč",
    email: "jan.kovac@email.com",
    confirmAdult: true,
    placement: "hrudník",
    size: "veľká",
    color: "color",
    description: "Portrét rodiny s krajinou v pozadí",
    references: ["https://example.com/ref9.jpg", "https://example.com/ref10.jpg"],
    imageUrl: null,
    notes: "Klient má fotky rodiny, chce ich spracovať",
    contactPreferenceEmail: true,
    contactPreferenceInstagram: false,
    contactPreferencePhone: true,
    instagram: null,
    phone: "+421 903 456 789",
    agreeMarketing: true,
    agreePrivacy: true,
    allergies: false,
    allergyDescription: null,
    healthIssues: false,
    healthIssueDescription: null,
    appointmentDate: new Date("2025-08-17"),
    appointmentTime: "10:00",
    duration: 6,
    status: "pending"
  },
  {
    fullName: "Mária Szabóová",
    email: "maria.szaboova@email.com",
    confirmAdult: true,
    placement: "rameno",
    size: "stredná",
    color: "blackwhite",
    description: "Mandala s geometrickými vzormi",
    references: ["https://example.com/ref11.jpg"],
    imageUrl: null,
    notes: "Klientka chce spirituálny význam",
    contactPreferenceEmail: true,
    contactPreferenceInstagram: true,
    contactPreferencePhone: false,
    instagram: "@maria_szabo",
    phone: null,
    agreeMarketing: false,
    agreePrivacy: true,
    allergies: false,
    allergyDescription: null,
    healthIssues: false,
    healthIssueDescription: null,
    appointmentDate: new Date("2025-08-20"),
    appointmentTime: "15:00",
    duration: 3,
    status: "rejected"
  },
  {
    fullName: "Tomáš Nagy",
    email: "tomas.nagy@email.com",
    confirmAdult: true,
    placement: "predlaktie",
    size: "malá",
    color: "color",
    description: "Logo obľúbenej kapely",
    references: ["https://example.com/ref12.jpg"],
    imageUrl: null,
    notes: "Klient je fanúšik kapely, chce ich logo",
    contactPreferenceEmail: false,
    contactPreferenceInstagram: true,
    contactPreferencePhone: false,
    instagram: "@tomas_nagy",
    phone: null,
    agreeMarketing: true,
    agreePrivacy: true,
    allergies: false,
    allergyDescription: null,
    healthIssues: false,
    healthIssueDescription: null,
    appointmentDate: new Date("2025-08-23"),
    appointmentTime: "12:00",
    duration: 2,
    status: "confirmed"
  },
  {
    fullName: "Katarína Vargaová",
    email: "katarina.vargaova@email.com",
    confirmAdult: true,
    placement: "chrbát",
    size: "veľká",
    color: "color",
    description: "Krajina s horami a jazerom",
    references: ["https://example.com/ref13.jpg", "https://example.com/ref14.jpg"],
    imageUrl: null,
    notes: "Klientka chce spomienku na dovolenku",
    contactPreferenceEmail: true,
    contactPreferenceInstagram: false,
    contactPreferencePhone: true,
    instagram: null,
    phone: "+421 904 321 098",
    agreeMarketing: true,
    agreePrivacy: true,
    allergies: false,
    allergyDescription: null,
    healthIssues: false,
    healthIssueDescription: null,
    appointmentDate: new Date("2025-08-26"),
    appointmentTime: "09:00",
    duration: 5,
    status: "pending"
  },
  {
    fullName: "Andrej Baláž",
    email: "andrej.balaz@email.com",
    confirmAdult: true,
    placement: "noha",
    size: "stredná",
    color: "blackwhite",
    description: "Skull s kvetmi a čiernou ružou",
    references: ["https://example.com/ref15.jpg"],
    imageUrl: null,
    notes: "Klient chce dark/gothic štýl",
    contactPreferenceEmail: true,
    contactPreferenceInstagram: true,
    contactPreferencePhone: false,
    instagram: "@andrej_balaz",
    phone: null,
    agreeMarketing: false,
    agreePrivacy: true,
    allergies: false,
    allergyDescription: null,
    healthIssues: false,
    healthIssueDescription: null,
    appointmentDate: new Date("2025-08-29"),
    appointmentTime: "14:00",
    duration: 4,
    status: "rescheduled"
  }
];

async function createDummyReservations() {
  try {
    console.log('Creating 10 dummy reservations...');
    
    for (const reservation of dummyReservations) {
      const created = await prisma.tattooAppointment.create({
        data: reservation
      });
      console.log(`✅ Created reservation for ${created.fullName} on ${created.appointmentDate.toLocaleDateString('sk-SK')} at ${created.appointmentTime}`);
    }
    
    console.log('🎉 All 10 dummy reservations created successfully!');
  } catch (error) {
    console.error('❌ Error creating dummy reservations:', error);
  } finally {
    await prisma.$disconnect();
  }
}

createDummyReservations(); 